.gitignore
package.json
readme.md

- adds readme
- adds npm start script
- cleans up pkg.json with my favorite cli, [fixpack](https://github.com/HenrikJoreteg/fixpack)
- adds .log to the .gitignore

add readme

---

lib/config.js
lib/index.js
lib/plugins/css_plugin.js
lib/plugins/jade_plugin.js
lib/plugins/plugin_utils.js
package.json
test/_helpers.js
test/css.js
test/fixtures/css/main.css

Ok, it's working. Now let me say that it's slightly janky and almost certainly needs some more tests, but it is fully functional.
The async tests eating all errors was quite a large issue and probably was the cause of this taking so long to figure out. Next work day my task will be to do a little refactoring and get us on a bit more stable of a foundation.
This PR also includes a couple other little cleanings and fixes. Sorry I should be more on top of separating these out, but I'll just call "early development" and hopefully be forgiven.

Css Plugin!

---

lib/plugins/plugin_utils.js

- this was failing for me locally, but working on the CI for some reason.

make getFilesFromGlob() pass ignores tests

---

readme.md

this had confused @elvingm a bit, so figured we'd explicitly document it until `roots.new` is done

better document sprout usage, for now

---

lib/config.js
readme.md
test/config_errors.js

Because sometimes that's necessary

Allow postcss options to be passed through

---

lib/config.js

my magnum opus :musical_score:

fix issue w/ adding postcss-import as first plugin

---

.babelrc
.travis.yml
bin/roots
lib/cli/clean.js
lib/cli/compile.js
lib/cli/index.js
lib/cli/new.js
lib/cli/watch.js
lib/config.js
lib/index.js
package.json
test/cli.js
test/new.js

New Command

---

lib/config.js
lib/plugins/fs_plugin.js
lib/plugins/jade_plugin.js

separate out fs plugin, mod plugin order

---

lib/config.js

Now it looks like this:
closes #89

Log out Browsersync External IP

---

lib/cli/index.js
lib/config.js
lib/errors.js
lib/index.js
lib/plugins/css_plugin.js
lib/plugins/fs_plugin.js
lib/plugins/jade_plugin.js
lib/plugins/plugin_utils.js
lib/plugins/static_plugin.js

- lots more jsdoc documentation
- remove .css extension from core parser
- remove extra browsersync options, allow unknowns

a variety of small changes

---

lib/config.js

fix :bug: with opts.env being set to null in cli

---

.github/issue_template.md
.github/pull_request_template.md

add issue and pr templates

---

readme.md

borrowed a bit form the roots readme

expand the why you should care section

---

lib/cli/new.js
lib/config.js
lib/index.js
lib/plugins/css_plugin.js
lib/plugins/jade_plugin.js
lib/plugins/plugin_utils.js
lib/plugins/static_plugin.js
package.json
test/cli.js
test/config_errors.js
test/fixtures/jade_dependencies/index.jade
test/fixtures/jade_dependencies/script.js
test/fixtures/jade_dependencies/style.css
test/jade.js
test/new.js
test/plugins.js
test/static.js

All our libraries have 100% coverage because that's how it's done, and spike will be no exception. Let's get it. :100:

[WIP] Coverage > :100:

---

lib/index.js
package.json
readme.md
test/new.js

Breaking changes in here, but they are good, promise.

Spike.new docs, extract inquirer, update options

---

lib/index.js
test/template.js

Template Options

---

lib/index.js
readme.md

Oops, forgot to do this before!
Also, maybe I should add tests for all the error conditions...

Add docs for template options

---

lib/index.js
package.json
test/_helpers.js
test/new.js

Template option for Spike.new

---

lib/index.js
readme.md
test/new.js
test/template.js

So I ran into a strange conflict during work on the CLI between the new and template commands' event terminology. This resolves is 😁

Switch up the event naming a bit

---

package.json
test/html.js
test/jade.js

This is a breaking change, as `defaults` must be changed to `plugins` for posthtml config.

Upgrade posthtml loader

---

lib/plugins/html_plugin.js
package.json

It was honestly ridiculous that we did this in the first place. I think I was just confused about life.

Remove additional dep add to html files

---

appveyor.yml
lib/plugin.js
package.json
yarn.lock

Windows Fixes!

---

readme.md

fix #257 change npms.io query string from term to q in README.md

---

package.json

Make them tests all green, ready for publish
