- package.json
- test/index.js
- [Standard](/feross/standard) is not aware of Babel by default - this PR adds a `standard` property to `package.json` that sets the `eslint` parser to `babel-eslint`. This _should supposedly_ obtain the config from `.babelrc`.
- Cleaned up the `npm scripts` somewhat - there is no need to use `node_modules/.bin/package` as `package` inside an `npm script` will automatically resolve to the binary. 
- Extracted the `lint` logic out to it's own script so tests need not be run if all you want is just to lint the files. 
- Added `pre-commit` linting to prevent invalid code from entering the remote repo - thanks to [Husky](/typicode/husky). Bypass this by passing `--no-verify` along with your `git` commands
Unfortunately, `standard` throws a non-zero exit which clutters the lint output with …
> Improve Standard Linting

- .travis.yml
- package.json
This is a separate PR from `async-tests` (to be merged into `async-tests`) in case we decide this isn't the best way forward and want to support older engines
I just discovered that we use `babel-preset-es2015-node-5` rather than `babel-preset-es2015`. The former only transpiles ES2015 features that Node v5 does not already support, whereas the latter transpiles everything. Therefore, it doesn't make sense to test Node `0.10`-`0.12` or `iojs` on Travis - since `roots-mini` doesn't support those engines. I've also added an `engines` field to `package.json` which should warn about this when `roots-mini` is installed.
> require node 5 and npm 3 engines

- bin/roots
- lib/cli/compile.js
- lib/cli/index.js
- lib/config.js
- lib/errors.js
- lib/index.js
- lib/plugins/css_plugin.js
- lib/plugins/jade_plugin.js
- lib/plugins/plugin_utils.js
- package.json
- readme.md
- test/_helpers.js
- test/ignores.js
ref: https://webpack.github.io/docs/node.js-api.html#error-handling
the tests will fail because it unearths some additional webpack errors that weren't coming back in the `err` param
```js
webpack(this.config, (err, stats) => { //...
```
---
in our configuration, we define the webpack config's `entry` as: 
```js
this.entry = { main: ['./app.js'] }
```
and it looks like webpack needs that file to actually exist because it throws:
```sh
Error: Cannot resolve 'file' or 'directory' ./app.js in /Users/kylemac/Sites/carrot/roots-mini/test/fixtures/dump_dirs
```
fwiw, we're catching the lack of an `app.js` file already here: https://github.com/carrot/roots-mini/blob/cli/lib/config.js#L106-L108
> CLI & Better Error Handling

- lib/cli/index.js
passing `server`, even when port was null was disrupting the logic that used `Object.assign()` to establish default hierarchy. i chose to add a conditional in the CLI logic, as opposed to convoluting the config logic. i'm open for better ideas though...
> don't set port by default on cli

- lib/config.js
- package.json
fixes #51 
I had to push the outputDir to the end of the array, as I couldn't find a Joi'ish way to go up the chain and get the value of `outputDir`
> ensure ./node_modules and outputDir aren't watched

- lib/config.js
- lib/plugins/jade_plugin.js
- lib/plugins/plugin_utils.js
- package.json
- intelligently rewrites deps from a dumpdir
- uses cheerio to traverse HTML
feel like there's optimizations to how we're doing the rewrites for files in dumpdirs. open to suggestions, just wanted to get a proof of concept in place first.
> walk HTML for dependencies and inject into webpack

- lib/config.js
this was breaking es6 usage when a `.babelrc` wasn't set.
> set defaults for babel-core/register

- lib/config.js
- lib/plugins/css_plugin.js
- lib/plugins/jade_plugin.js
- lib/plugins/plugin_utils.js
- lib/plugins/static_plugin.js
now the jade plugin (presumptively because it's listed first in the `plugins` array) only searches the fs once and then shares that info w/ the other (css, static) plugins by tacking it to the webpack compiler object (`compiler.options.files`)
i'm using `compiler.options.files` but it could be just `compiler.files` if we wanted, but since we're already using `compiler.options` for `locals`, it'd be nice to have it in 1 place. also, `compiler.options` isn't an unwieldily monster object like `compiler` is. perhaps longterm we'll namespace like `compiler.roots` - but for now this does the trick.
> glob the filesystem only once and share w/ plugins

- lib/config.js
- package.json
- updates ava
- uses explicit loaders as to not cause unforeseen collisions
- allow a loader override by defining it in your project's `package.json` 
there's more work to be done to be able to accept custom loaders in `app.js`, but these changes are the first step. we can address custom loader definitions in a future PR
> Loader hotfix

- lib/index.js
- lib/plugins/fs_plugin.js
- test/watch.js
- Watch compiles only once, and with cleaner code as well
- Fs plugin now works in watch and compile mode
Closes #67
> Watch mode fixes

- lib/config.js
- lib/index.js
- lib/plugins/css_plugin.js
- lib/plugins/fs_plugin.js
- lib/plugins/jade_plugin.js
- lib/plugins/plugin_utils.js
- lib/plugins/static_plugin.js
- test/watch.js
- plugins utils significant refactor
- make some plugin utils available on compiler opts
- add new files to the watcher when created
Still todo, add a test for the new file watcher add!
Closes #59
> [WIP] Refactors, adds new files interactively

- lib/index.js
This speeds up new project initialization by about 60%
> only install production deps for new templates

- lib/config.js
Since plugins can only access the webpack config option, we need to make any options passed in to spike available through this object. This is in preparation for separating out the plugin utils 😬
> some option updates

- lib/config.js
- lib/index.js
- lib/plugins/css_plugin.js
- lib/plugins/fs_plugin.js
- lib/plugins/jade_plugin.js
- lib/plugins/plugin_utils.js
- lib/plugins/static_plugin.js
- package.json
- test/compile.js
So this refactor gets us to a place where, if we could get the external `spike-utils` module working, it would work, and we could swap it out in one place. However, it doesn't work due to a very nasty issue deep in webpack's core. Either way, we keep the same functionality with this PR, and get the structure we need to immediately switch in the utils once they are ready, so 🚒
> Refactor plugin utils

- lib/config.js
- lib/plugins/static_plugin.js
- package.json
- test/fixtures/static_plugins/plugin.js
Slims down the dependencies, cuts some unnecessary code, puts the static plugin on a solid base.
> file-loader -> source-loader

- lib/plugins/css_plugin.js
- lib/plugins/fs_plugin.js
- lib/plugins/jade_plugin.js
- lib/plugins/static_plugin.js
- package.json
Convert up to latest version of spike-util, refactor `getFilesFromGlob` to be much more clean and efficient, and thoroughly annotate because it's one of our more complex methods.
> New utils / Assorted Refactors

- lib/config.js
- test/ignores.js
> Ignores fix

- lib/config.js
- lib/index.js
- test/_helpers.js
- test/app_config.js
> Config options refactor

- lib/config.js
- test/app_config.js
- test/fixtures/app_config/app.js
Relates to static-dev/spike#38
Referenced PR exposed issue that nested options objects being passed from the API are not merged properly with options from `App.js` – Because `Object.assign` copies the full reference over if the value of a key:value pair is an object. This was leading to server options set in `App.js` being ignored. 
This PR fixes this issue by changing the way options are merged to use a method suitable for nested objects. 
There is a new test to check that the merge is operating properly.
> Fix merging of nested options objects from API

- lib/plugin.js
- test/fixtures/plugins/custom_output.html
- test/fixtures/plugins/plugin.js
- test/plugins.js
> Add spike processed file outPath option

- lib/config.js
- test/fixtures/plugins/after_plugin.js
- test/fixtures/plugins/app.js
- test/fixtures/plugins/plugin.js
- test/plugins.js
- yarn.lock
This lets user-added plugins access spike-generated assets. Specifically this makes the offline plugin work perfectly for generating service workers.
> Add `afterSpikePlugins` option

- lib/config.js
- test/environments.js
- test/fixtures/environments/app.doge.js
- test/fixtures/environments/app.js
So this will make writing conditionals in config files much easier, without needing to set `NODE_ENV` unless its required by some other lib ✨
> Spike Env Variable

- lib/config.js
- test/config_errors.js
I added a `Config.server.proxy` option for browser-syn, to allow proxy to different server in the background (which then handles serving the spike built files). This option must be `string` or `object` with key `target`, and if is defined, `Config.server.server` must be set to `false`.
I added all of this to Joi schema and put the `Config.server.server.baseDir` setting behind check for existence of server.
> Browser sync proxy

- lib/index.js
The tests kept failing when running multiple times, because this Spike.new tries to install NPM dependencies without a check for existence of a package.json file, so if the new Spike project was in a child directory of another node project, it would call the 'npm install --production' on the parent instead — which is a problem, especially for repositories using yarn.
This add a synchronous explicit check for 'package.json' before trying to install.
> Check for package.json before trying to install dependencies
